platform :ios, '9.0'
use_frameworks!

target ‘Learning-PureLayout’ do
    pod 'PureLayout'
    pod 'SideMenu'
end


post_install do |installer|
    # NOTE: If you are using a CocoaPods version prior to 0.38, replace `pods_project` with `project` on the below line
    installer.pods_project.targets.each do |target|
        if target.name.end_with? "PureLayout"
            target.build_configurations.each do |build_configuration|
                if build_configuration.build_settings['APPLICATION_EXTENSION_API_ONLY'] == 'YES'
                    build_configuration.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = ['$(inherited)', 'PURELAYOUT_APP_EXTENSIONS=1']
                end
            end
        end
    end
end
